### PR TITLE
Add check for the CHG line in .mol files

### PR DESCRIPTION
**Pull request by ralf-meyer**
Found additional problems with the charges in ligand .mol files. @gianmarco-terrones could you help me figure out if the newly added test makes sense and what the correct charge for the 4 failing test cases should be?

### CODE REVIEW

**Comment by gianmarco-terrones** [comment]
@ralf-meyer Thanks for doing this! The failures are all associated with .mol files with negative charges.

The line `assert charge == sum([int(s) for s in sp[4::2]])` is missing the negative signs, I think.

**Comment by ralf-meyer** [comment]
Thanks for the fast response! The 4 failing cases are:
```
FAILED tests/test_ligands.py::test_ligands_dict[edta] - assert -4 == 0
FAILED tests/test_ligands.py::test_ligands_dict[mebenzenedithiol] - assert -2 == 0
FAILED tests/test_ligands.py::test_ligands_dict[methyl] - assert -1 == 0
FAILED tests/test_ligands.py::test_ligands_dict[phenylbenzoxazole] - assert -1 == 0
```
The left hand side corresponds to the charge defined in the .mol files, the right hand side is the charge in `ligands.dict`. So the question is which one should I keep? I will also try to improve the readability of the test case!

**Comment by ralf-meyer** [comment]
Thanks for the quick reply! The 4 failing cases are:
```
FAILED tests/test_ligands.py::test_ligands_dict[edta] - assert -4 == 0
FAILED tests/test_ligands.py::test_ligands_dict[mebenzenedithiol] - assert -2 == 0
FAILED tests/test_ligands.py::test_ligands_dict[methyl] - assert -1 == 0
FAILED tests/test_ligands.py::test_ligands_dict[phenylbenzoxazole] - assert -1 == 0
```
They fail at the line:
`assert lig.charge == charge`
because I fixed the "formatting errors" in the corresponding .mol files. The left hand side corresponds the the charge in the .mol file, the right hand side is the charge defined in `ligands.dict`. The question is, which one is correct, which one should I keep?

Edit: I just realized I already fixed one of those "failures": carboxyl had a charge of 0 listed in the `ligands.dict` file which I changed to -1 (following the .mol). Is that the correct course of action for the remaining 4 failures?

**Comment by gianmarco-terrones** [comment]
I just merged changes to ligands_dict to master. In all cases `ligands.dict` was wrong and the charge from the .mol file was correct.

**Comment by gianmarco-terrones** [comment]
Hmm not sure why it failed, it was passing locally

**Comment by ralf-meyer** [comment]
I think it still reports the failure from my most recent commit. Your fix should pass the tests

**Comment by gianmarco-terrones** [comment]
Cool. #90 does not have the updated comments in test_ligands that you added here; I can add them later

**Pull request closed without merging**
