### PR TITLE
Updated naming schemes for input and jobscript files

### PR DESCRIPTION
**Pull request by husainadamji**
Modified naming schemes of automatically generated input and jobscript files so that they are named according to the molSimplify generated xyz file instead of "terachem_input" and "jobscript"

Updated lines written in terachem .in file (e.g., inclusion of dftgrid 2 and precision double).

Changed args Namespace so that default runtyp is not 'energy' but 'minimize'

### CODE REVIEW

**Review by dbkchu — APPROVED** [review]
Adjusted to pass checks

**Review by dbkchu — DISMISSED** [review]
Needs updates to test cases to reflect changes in generated scripts

**Comment by ralf-meyer** [comment]
Added the test cases that @dbkchu  requested and added a `jobmanager` input flag that toggles this behavior. Still not sure this is the best way to do it but at least we will not break anything else this way!

**Review by ralf-meyer — APPROVED** [review]

**Comment by gianmarco-terrones** [comment]
Should this be merged?

**Pull request merged**
